name: promilio_proj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # network
  http: ^1.2.1
  dio: ^5.5.0+1
  crypto: ^3.0.3
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  # UI
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  share_plus: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
